name: build-docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker-c3poa:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push c3poa
        uses: docker/build-push-action@v5
        with:
          context: ./deps/C3POa
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lr_c3poa
  docker-align:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push minimap2 + samtools
        uses: docker/build-push-action@v5
        with:
          context: ./deps/align
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lr_align
  docker-pybio:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push pybio
        uses: docker/build-push-action@v5
        with:
          file: deps/pybio/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lr_pybio:py310, ${{ secrets.DOCKER_HUB_USERNAME }}/lr_pybio:latest